// GENERATED by tools/parse_workbook.py — do not edit by hand.
// Read-only reference data. Source: Course_Tracker.xlsx  (roster mode: initials)

export const cs440Groups = [
  {
    "group": "Group 1",
    "members": [
      "H.",
      "M.",
      "S.",
      "Nick"
    ],
    "facilitates": "Wk 2 Mon 08/31 · Software Lifecycle, Working with Users",
    "mine": true
  },
  {
    "group": "Group 2",
    "members": [
      "O.",
      "M.",
      "S.",
      "S."
    ],
    "facilitates": "Wk 2 Wed 09/02 · Team & Communication",
    "mine": false
  },
  {
    "group": "Group 3",
    "members": [
      "T.",
      "A.",
      "U.",
      "D."
    ],
    "facilitates": "Wk 3 Mon 09/07 · Design Documents",
    "mine": false
  },
  {
    "group": "Group 4",
    "members": [
      "P.",
      "J.",
      "K.",
      "A."
    ],
    "facilitates": "Wk 3 Wed 09/09 · Software Architecture",
    "mine": false
  },
  {
    "group": "Group 5",
    "members": [
      "Nick",
      "S.",
      "A.",
      "P."
    ],
    "facilitates": "Wk 4 Mon 09/14 · Microservices",
    "mine": true
  },
  {
    "group": "Group 6",
    "members": [
      "S.",
      "U.",
      "J.",
      "H."
    ],
    "facilitates": "Wk 5 Mon 09/21 · Software Quality",
    "mine": false
  },
  {
    "group": "Group 7",
    "members": [
      "D.",
      "K.",
      "M.",
      "O."
    ],
    "facilitates": "Wk 6 Mon 09/28 · Code Review and Risk",
    "mine": false
  },
  {
    "group": "Group 8",
    "members": [
      "A.",
      "S.",
      "M.",
      "T."
    ],
    "facilitates": "Wk 7 Mon 10/05 · Metrics & Measurements",
    "mine": false
  },
  {
    "group": "Group 9",
    "members": [
      "H.",
      "O.",
      "T.",
      "P."
    ],
    "facilitates": "Wk 9 Mon 10/19 · Static Analysis",
    "mine": false
  },
  {
    "group": "Group 10",
    "members": [
      "M.",
      "M.",
      "A.",
      "J."
    ],
    "facilitates": "Wk 10 Mon 10/26 · Dynamic Analysis",
    "mine": false
  },
  {
    "group": "Group 11",
    "members": [
      "S.",
      "S.",
      "U.",
      "K."
    ],
    "facilitates": "Wk 11 Mon 11/02 · Reliably Releasing Software",
    "mine": false
  },
  {
    "group": "Group 12",
    "members": [
      "Nick",
      "S.",
      "D.",
      "A."
    ],
    "facilitates": "Wk 12 Mon 11/09 · Ethics",
    "mine": true
  }
];

export const myGroups = [
  "Group 1",
  "Group 12",
  "Group 5"
];

export const cs440Schedule = [
  {
    "wk": "1",
    "date": "2026-08-24",
    "day": "Mon",
    "topic": "Course Overview, Software Archeology",
    "reading": "2,3",
    "seText": "4",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "1",
    "date": "2026-08-26",
    "day": "Wed",
    "topic": "Group Icebreaker (ICL Plank)",
    "reading": "2,3",
    "seText": "4",
    "facilitators": "Josh",
    "due": "⇢ M 08/31: set up meeting w/ client",
    "mine": false
  },
  {
    "wk": "2",
    "date": "2026-08-31",
    "day": "Mon",
    "topic": "Software Lifecycle, Working with Users",
    "reading": "5",
    "seText": "2a, 4",
    "facilitators": "Group 1",
    "due": "M 08/31: set up meeting w/ client",
    "mine": true
  },
  {
    "wk": "2",
    "date": "2026-09-02",
    "day": "Wed",
    "topic": "Team & Communication",
    "reading": "6",
    "seText": "6",
    "facilitators": "Group 2",
    "due": "T 09/01: resume 1st draft",
    "mine": false
  },
  {
    "wk": "3",
    "date": "2026-09-07",
    "day": "Mon",
    "topic": "Design Documents",
    "reading": "9",
    "seText": "15",
    "facilitators": "Group 3",
    "due": "T 09/08: client interview report (as meeting minutes)",
    "mine": false
  },
  {
    "wk": "3",
    "date": "2026-09-09",
    "day": "Wed",
    "topic": "Software Architecture",
    "reading": "7",
    "seText": "22",
    "facilitators": "Group 4",
    "due": "F 09/11: resume final, DISC survey",
    "mine": false
  },
  {
    "wk": "4",
    "date": "2026-09-14",
    "day": "Mon",
    "topic": "Microservices",
    "reading": "8",
    "seText": "27",
    "facilitators": "Group 5",
    "due": "",
    "mine": true
  },
  {
    "wk": "4",
    "date": "2026-09-16",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "F 09/18: SRS draft",
    "mine": false
  },
  {
    "wk": "5",
    "date": "2026-09-21",
    "day": "Mon",
    "topic": "Software Quality",
    "reading": "16",
    "seText": "9",
    "facilitators": "Group 6",
    "due": "",
    "mine": false
  },
  {
    "wk": "5",
    "date": "2026-09-23",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "6",
    "date": "2026-09-28",
    "day": "Mon",
    "topic": "Code Review and Risk",
    "reading": "10",
    "seText": "14",
    "facilitators": "Group 7",
    "due": "Self/Peer Evaluation 1 (in-class)",
    "mine": false
  },
  {
    "wk": "6",
    "date": "2026-09-30",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "F 10/02: SRS final",
    "mine": false
  },
  {
    "wk": "7",
    "date": "2026-10-05",
    "day": "Mon",
    "topic": "Metrics & Measurements",
    "reading": "4",
    "seText": "11",
    "facilitators": "Group 8",
    "due": "",
    "mine": false
  },
  {
    "wk": "7",
    "date": "2026-10-07",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "8",
    "date": "2026-10-12",
    "day": "Mon",
    "topic": "Fall Break (no class)",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "8",
    "date": "2026-10-14",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "9",
    "date": "2026-10-19",
    "day": "Mon",
    "topic": "Static Analysis",
    "reading": "15",
    "seText": "26",
    "facilitators": "Group 9",
    "due": "",
    "mine": false
  },
  {
    "wk": "9",
    "date": "2026-10-21",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "10",
    "date": "2026-10-26",
    "day": "Mon",
    "topic": "Dynamic Analysis",
    "reading": "17",
    "seText": "16, 18",
    "facilitators": "Group 10",
    "due": "",
    "mine": false
  },
  {
    "wk": "10",
    "date": "2026-10-28",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "11",
    "date": "2026-11-02",
    "day": "Mon",
    "topic": "Reliably Releasing Software",
    "reading": "21",
    "seText": "29, 30",
    "facilitators": "Group 11",
    "due": "Self/Peer Evaluation 2 (in-class)",
    "mine": false
  },
  {
    "wk": "11",
    "date": "2026-11-04",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "12",
    "date": "2026-11-09",
    "day": "Mon",
    "topic": "Ethics",
    "reading": "20",
    "seText": "8",
    "facilitators": "Group 12",
    "due": "",
    "mine": true
  },
  {
    "wk": "12",
    "date": "2026-11-11",
    "day": "Wed",
    "topic": "Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "13",
    "date": "2026-11-16",
    "day": "Mon",
    "topic": "Department Assessment (CS Exam)",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "Presentation Slides (before class)",
    "mine": false
  },
  {
    "wk": "13",
    "date": "2026-11-18",
    "day": "Wed",
    "topic": "Final Project Meeting",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "14",
    "date": "2026-11-23",
    "day": "Mon",
    "topic": "Senior Survey",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "Presentation Slides (before class)",
    "mine": false
  },
  {
    "wk": "14",
    "date": "2026-11-25",
    "day": "Wed",
    "topic": "Thanksgiving Break (no class)",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "15",
    "date": "2026-11-30",
    "day": "Mon",
    "topic": "Rehearsal (Tue Dec-01 group)",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "Presentation Slides (before class)",
    "mine": false
  },
  {
    "wk": "15",
    "date": "2026-12-02",
    "day": "Wed",
    "topic": "Rehearsal (Thu Dec-03 group)",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "",
    "mine": false
  },
  {
    "wk": "*",
    "date": "2026-12-07",
    "day": "Mon",
    "topic": "Project Report, Wrap-up",
    "reading": "",
    "seText": "",
    "facilitators": "",
    "due": "Final Deliverable; Self/Peer Evaluation 3; Manager Evaluation",
    "mine": false
  }
];

export const cs360Schedule = [
  {
    "wk": "1",
    "date": "2026-08-24",
    "topic": "Overview, intro, ER model",
    "reading": "1-3, 5",
    "due": ""
  },
  {
    "wk": "2",
    "date": "2026-08-31",
    "topic": "Data Modeling (ER, EER)",
    "reading": "3, 4",
    "due": "hw0"
  },
  {
    "wk": "3",
    "date": "2026-09-07",
    "topic": "(Relational Database), Relational Algebra, intro to MySQL — Project Group Formation",
    "reading": "(5), 8, 6",
    "due": "hw1"
  },
  {
    "wk": "4",
    "date": "2026-09-14",
    "topic": "ER-to-schema, Aggregate, Complex Query — intro to HTML/PHP",
    "reading": "9.1-9.2, 7.1, 11",
    "due": "hw2"
  },
  {
    "wk": "5",
    "date": "2026-09-21",
    "topic": "PHP",
    "reading": "11",
    "due": "Exam 1"
  },
  {
    "wk": "6",
    "date": "2026-09-28",
    "topic": "Complex SQL — Project ERD, table setup w/ sample data",
    "reading": "7.1",
    "due": "hw3"
  },
  {
    "wk": "7",
    "date": "2026-10-05",
    "topic": "Functional Dependencies, Normalization — Project Status Meeting 1",
    "reading": "14.1-14.3",
    "due": "hw4"
  },
  {
    "wk": "8",
    "date": "2026-10-12",
    "topic": "Fall Break (no class on Tuesday) — Normalization",
    "reading": "",
    "due": ""
  },
  {
    "wk": "9",
    "date": "2026-10-19",
    "topic": "Disk Storage and File Structures — Project Status Meeting 2",
    "reading": "16",
    "due": "hw5"
  },
  {
    "wk": "10",
    "date": "2026-10-26",
    "topic": "File Structure and Hashing",
    "reading": "16",
    "due": "Exam 2"
  },
  {
    "wk": "11",
    "date": "2026-11-02",
    "topic": "File Structure and Hashing",
    "reading": "16",
    "due": "hw6"
  },
  {
    "wk": "12",
    "date": "2026-11-09",
    "topic": "Transactions — Project Status Meeting 3",
    "reading": "20",
    "due": "hw7"
  },
  {
    "wk": "13",
    "date": "2026-11-16",
    "topic": "Indexing",
    "reading": "17",
    "due": "hw8"
  },
  {
    "wk": "14",
    "date": "2026-11-23",
    "topic": "Query Processing and Optimization — Thanksgiving Break (no class on Thursday)",
    "reading": "18-19",
    "due": ""
  },
  {
    "wk": "15",
    "date": "2026-11-30",
    "topic": "Graph Database",
    "reading": "",
    "due": "Exam 3"
  },
  {
    "wk": "*",
    "date": "2026-12-07",
    "topic": "Final project submission (11:59 pm)",
    "reading": "",
    "due": ""
  }
];
